# Generated by Django 3.0.7 on 2020-06-19 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Wait', max_length=10)),
                ('file', models.FileField(upload_to='upload/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['asf', 'avi', 'flv', 'mpg', 'mpeg', 'mp4', 'mov', 'webm', 'mkv', 'wmv', 'ogv'])])),
                ('filesize', models.CharField(default=None, max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('aimodel_alias', models.CharField(choices=[('1x2_3c', 'pikavue_1x2_3c'), ('4x2_3c', 'pikavue_4x2_3c'), ('1x4_3c', 'pikavue_1x4_3c'), ('4x4_3c', 'pikavue_4x4_3c')], default='1x2_3c', max_length=255)),
                ('target', models.FileField(default=None, null=True, upload_to='upscale/')),
                ('width', models.IntegerField(default=None, null=True)),
                ('height', models.IntegerField(default=None, null=True)),
                ('vframeRate', models.CharField(blank=True, max_length=5)),
                ('scale', models.FloatField(default=4)),
                ('afilesize', models.CharField(default=None, max_length=20)),
                ('up_width', models.IntegerField(default=None, null=True)),
                ('up_height', models.IntegerField(default=None, null=True)),
                ('start_dt', models.DateTimeField(default=None, null=True)),
                ('complete_dt', models.DateTimeField(default=None, null=True)),
                ('processed_time', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
